#!/usr/bin/env python3
# How many distinct terms are in the sequence generated by a**b for 2 <= a <= 100 and 2 <= b <= 100?

nums = []

for a in range(2, 101):
	for b in range(2, 101):
		if a**b not in nums:
			nums.append(a**b)

print(len(nums))